"""
Query Processor Constants
Stopwords (German and English), intent patterns, and synonyms
"""

from .models import QueryIntent

# Deutsche Stopwords (erweitert)
GERMAN_STOPWORDS = {
    # Artikel
    "der",
    "die",
    "das",
    "den",
    "dem",
    "des",
    "ein",
    "eine",
    "einer",
    "eines",
    "einem",
    "einen",
    # Pronomen
    "ich",
    "du",
    "er",
    "sie",
    "es",
    "wir",
    "ihr",
    "mein",
    "dein",
    "sein",
    "unser",
    "euer",
    "mir",
    "dir",
    "ihm",
    "uns",
    "euch",
    "ihnen",
    "mich",
    "dich",
    "sich",
    # Konjunktionen
    "und",
    "oder",
    "aber",
    "doch",
    "sondern",
    "denn",
    "weil",
    "dass",
    "wenn",
    "als",
    "ob",
    "obwohl",
    "damit",
    "bevor",
    "nachdem",
    "während",
    "bis",
    "seit",
    # Präpositionen
    "in",
    "im",
    "an",
    "am",
    "auf",
    "aus",
    "bei",
    "mit",
    "nach",
    "von",
    "zu",
    "zum",
    "zur",
    "für",
    "gegen",
    "ohne",
    "um",
    "durch",
    "über",
    "unter",
    "vor",
    "hinter",
    "zwischen",
    # Hilfsverben
    "ist",
    "sind",
    "war",
    "waren",
    "wird",
    "werden",
    "wurde",
    "wurden",
    "hat",
    "haben",
    "hatte",
    "hatten",
    "kann",
    "können",
    "muss",
    "müssen",
    "soll",
    "sollen",
    "will",
    "wollen",
    "darf",
    "dürfen",
    "mag",
    "mögen",
    "möchte",
    "möchten",
    # Adverbien
    "nicht",
    "sehr",
    "mehr",
    "viel",
    "wenig",
    "ganz",
    "alle",
    "jeder",
    "kein",
    "keine",
    "auch",
    "noch",
    "nur",
    "schon",
    "bereits",
    "immer",
    "oft",
    "manchmal",
    "niemals",
    # Fragewörter (teilweise behalten für Intent-Erkennung)
    "was",
    "wie",
    "wer",
    "wen",
    "wem",
    "wessen",
    "wo",
    "wohin",
    "woher",
    "wann",
    "warum",
    "weshalb",
    "wieso",
    "welche",
    "welcher",
    "welches",
    # Sonstiges
    "ja",
    "nein",
    "doch",
    "also",
    "denn",
    "etwa",
    "vielleicht",
    "ziemlich",
}

ENGLISH_STOPWORDS = {
    "a",
    "an",
    "the",
    "and",
    "or",
    "but",
    "not",
    "nor",
    "if",
    "then",
    "so",
    "of",
    "in",
    "on",
    "at",
    "to",
    "for",
    "from",
    "by",
    "with",
    "about",
    "into",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "am",
    "do",
    "does",
    "did",
    "have",
    "has",
    "had",
    "can",
    "could",
    "will",
    "would",
    "should",
    "shall",
    "may",
    "might",
    "must",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "its",
    "our",
    "their",
    "this",
    "that",
    "these",
    "those",
    "what",
    "which",
    "who",
    "whom",
    "whose",
    "when",
    "where",
    "why",
    "how",
    "there",
    "here",
    "any",
    "some",
    "all",
    "no",
    "yes",
    "please",
    "tell",
}

# Both languages at once: the widget answers in the user's language, and a
# question can mix them ("Wie funktioniert das Deployment?").
STOPWORDS = GERMAN_STOPWORDS | ENGLISH_STOPWORDS

# Intent-Patterns
INTENT_PATTERNS = {
    QueryIntent.DEFINITION: [
        r"what\s+(is|are)\s+",
        r"meaning\s+of\s+",
        r"was\s+(ist|sind)\s+",
        r"definition\s+(von|für)\s+",
        r"bedeutet\s+",
        r"bedeutung\s+(von|für)\s+",
    ],
    QueryIntent.EXPLANATION: [
        r"how\s+(do|does|can|to)\s+",
        r"explain\s+",
        r"wie\s+(funktioniert|arbeitet|geht)\s+",
        r"erkläre\s+",
        r"erklärung\s+(von|für)\s+",
        r"wie\s+kann\s+",
    ],
    QueryIntent.EXAMPLE: [
        r"example\s+of\s+",
        r"beispiel\s+(für|von)\s+",
        r"zeige?\s+beispiel",
        r"gibt\s+es\s+beispiele",
    ],
    QueryIntent.COMPARISON: [
        r"difference\s+between\s+",
        r"\s+vs\.?\s+",
        r"\s+versus\s+",
        r"\s+gegen\s+",
        r"unterschied\s+(zwischen|von)\s+",
        r"vergleich\s+(zwischen|von)\s+",
    ],
    QueryIntent.LIST: [
        r"list\s+(of|all)\s+",
        r"liste\s+(von|der|aller)\s+",
        r"alle\s+",
        r"welche\s+arten\s+",
        r"typen\s+(von|der)\s+",
    ],
}

# Synonyms for query expansion, keyed by lower-case keyword. Empty by default:
# useful synonyms depend on the wiki's vocabulary. Add entries such as
#   "vacation": ["leave", "holiday", "pto"],
# and the first two of each list are searched alongside the keyword.
SYNONYMS: dict = {}
